### ISSUE TITLE
Print link cost in the graph

### ISSUE THREAD

**Issue by rbeumer** [Vadims06/topolograph#17]
Right now you can hover over a link to see the cost but that is not as convenient if I quickly want to compare multiple links and their cost.

It would be an idea to have an option to visualize the cost for links with a color or number. If the cost is not equal on both sides you could maybe print the cost on both sides to show the perspective.

**Comment by Vadims06** [comment]
Hi @rbeumer , good idea, but if you would like to find all links with not equal cost on both sides - go to Analytics -> Unidirectional and Asymmetric Links. It will colored all asymmetric links on the graph.
Hope it will work for you.

**Comment by rbeumer** [comment]
Hi @Vadims06. The use case I'm thinking about is mostly to have a quick overview of alle metrics in your network by printing them on your links. Right now you have to hover over the interface to see the metric cost which is less convenient :)

**Comment by Vadims06** [comment]
@rbeumer got it, try to implement.

**Comment by Vadims06** [comment]
Hi @rbeumer ,
I'm excited to announce that your feature request is implemented in https://github.com/Vadims06/topolograph/releases/tag/v2.30. Visjs is still not supported `LabelFrom`, `LabelTo`, so I implemented it on my own. It has been past about 2 years since you created this request, but all this time I keep this task in my backlog. Not sure if it is actual for you now, but check new version of Topolograph, it has OSPF monitoring.
